
##################################################
# This script contains several useful functions  #
# for the analysis of chronic irradiated SCC     #
# cell lines for my PhD                          #
##################################################




######################################################
#                                                    #
# 1. Functions to ingest data in a reproducible way  #
#                                                    #
######################################################

load_Fireplex_data_PhD <- function(filename = "200619_chronic_irr_normalized.csv", threshold)
{
  # check if required package is installed and load it
  if (!require(dplyr)) install.packages("dplyr")
  library(dplyr)
  
  #load data and change hyphens to underscores so r does not confuse a hyphen with minus
  dat <- read_csv(filename)
  names(dat) <- str_replace_all(names(dat), "-","_")
  # clean up the data, convert to tidy format and replace negative expression values with 0 as expression cannot be negative
  dat_f <- dat %>% 
    select(-Messung) %>%
    filter(cell_line != "HaCaT") %>%
    gather(miRNA, expression, -c(ID,cell_line, Irradiation)) %>% 
    mutate(expression = ifelse(expression < 0, 0, expression))  
  # index miRNAs with a median expression below the threshold
  ind <- dat_f %>%
    group_by(miRNA) %>%
    filter(median(expression, na.rm=TRUE) <= threshold) %>%
    .$miRNA %>% 
    unique() 
  # omit indexed miRNAs 
  dat_f %>% 
    filter(!miRNA %in% ind) %>%
    mutate(log_exp = log2(expression+1)) %>%
    mutate(miRNA = str_replace_all(miRNA, "hsa_", "")) %>%
    mutate(miRNA = str_replace_all(miRNA, "_","-")) %>%
    mutate(cell_line = str_replace_all(cell_line, "-","_"))
}

######################################################
#                                                    #
#        2. Data manipulation                        #
#                                                    #
######################################################

# ..................................................................................................................
# this function is used to extract clusters from a Heatmap object generated with ComplexHeatmap #

# Arguments                                                                                             #
#  - data: scaled data which was the iput to generate Heatmap                                           #
#  - HeatmapObj: Heatmap object generated with the Heatmap() function of the ComplexHeatmap package     #
#  - sampleName: Name of the column containing sample IDs                                               #
#  - sampleClust: Name of the clusters generated by clustering the samples (columns in the Heatmap)     #
#  - geneName: Name of the column containing genes/miRNAs                                               #
#  - geneClust: Name of the clusters generated by clustering the genes/miRNAs (rows in the Heatmap)     #

extract_clusters <- function(data, HeatmapObj, sampleName, sampleClust, geneName, geneClust){
  mat <- data
  # loops to extract samples (columns) from the cluster
  for (i in 1:length(column_order(HeatmapObj))){   if (i == 1) {
    clu <- t(t(colnames(mat[,column_order(HeatmapObj)[[i]]])))
    out <- cbind(clu, paste(toupper(letters[i])))
    colnames(out) <- c(sampleName, sampleClust)   } else {
      clu <- t(t(colnames(mat[,column_order(HeatmapObj)[[i]]])))
      clu <- cbind(clu, paste(toupper(letters[i])))
      out <- rbind(out, clu)   } 
  }
  colClust <- as.data.frame(out) 
  
  # function to extract miRNAs/genes (rows) from the cluster
  for (i in 1:length(row_order(Ht))){   if (i == 1) {
    clu <- t(t(rownames(mat[row_order(Ht)[[i]],])))
    out <- cbind(clu, paste("cluster", i, sep=""))
    colnames(out) <- c(geneName, geneClust)     } else {
      clu <- t(t(rownames(mat[row_order(Ht)[[i]],])))
      clu <- cbind(clu, paste("cluster",i, sep=""))
      out <- rbind(out, clu)    } 
  }
  rowClust <- as.data.frame(out)
  
  res <- list(colClust,rowClust)
  names(res) <- c(sampleClust, geneClust)
  return(res)
}



# ..................................................................................................................
# this function is used to calculate fold changes and pvalues in clusters extracted out of Heatmap #

# Function to extract fold changes and p-values of clusters
summary_clusters <- function(ls, miRcluster, cellcluster){
  # filter data for miRNA cluster i and combine data from cell cluster B and C as we wanna compare cluster A to the rest as the Heatmap indicates upregulation
  data <- ls[[miRcluster]] %>%
    mutate(cellCluster = ifelse(cellCluster == cellcluster, cellcluster, "ref")) %>%
    select(-miRCluster)
  # calculate FoldChange of the specified cluster vs the rest
  FC <- data %>%
    group_by(miRNA, cellCluster) %>%
    summarize(mean = mean(log_exp)) %>%
    ungroup() %>%
    group_by(miRNA) %>%
    summarize(logFC = mean[cellCluster==cellcluster]-mean[cellCluster =="ref"])
  # calculate pvalues 
  p_val <- data %>% 
    group_by(miRNA) %>%
    t_test(log_exp~cellCluster) %>%
    adjust_pvalue(method = "fdr")
  joined <- left_join(p_val, FC) %>% 
    mutate(FC = 2^logFC) %>%
    select(c(miRNA,FC, p.adj)) %>%
    setNames(c("miRNA", "FC","pvalue"))
  return(joined)
}



# ..................................................................................................................
# this function is used to drop attributes of a list #
drop_attr <- function(x) {
  for (i in length(x)) attr(x[[i]], "names") <- NULL
  return(x)
}


######################################################
#                                                    #
#        3. Plotting and significance Tests          #
#                                                    #
######################################################


# ..................................................................................................................
# this function is used to ensure a uniform theme and layout is used in each plot #

# Arguments                                                     #
#  - axis.text.size: Size of the axes                           #
#  - Legend: logical indicating if legend should be printed     #
theme_PhD <- function(axis.text.size=10, Legend = TRUE,...){
  
  theme_custom <- theme_pubr()+
    theme(axis.title.x=element_blank(),
          axis.text.x = element_text(face = "bold", size=axis.text.size),
          axis.text.y = element_text(face = "bold", size=axis.text.size),
          axis.title.y = element_text(face = "bold", size = axis.text.size+1),
          panel.grid.minor=element_blank(),
          strip.text.x = element_text(face = "bold", size = axis.text.size+1),
          strip.background=element_blank(),
          panel.spacing = unit(1, "lines"), ...) 
  
  
  if(Legend == TRUE) {
    theme_custom + theme(legend.key.size = unit(1,"line"))
  } else {
    theme_custom + theme(legend.position = "none")
  }
}

# ..................................................................................................................








